export const ArmsWorkouts = [
{
  "id": 1,
  "title": "Seated Dumbbell Curls",
  "description": "An isolation exercise targeting the biceps, helping to build arm strength and muscle definition.",
    "image": require('@/assets/images/menu/StandingEZBarCurls.png'),
   "videoUrl": 'https://www.youtube.com/embed/RJa4kG1N3d0',
         "instructions": [
             "Sit down on a flat bench with a dumbbell in each hand resting on your thighs. (The palms of your hands should be facing each other).",
             "Lower yourself down until you’re lying flat. The dumbbell should remain close to your chest.",
             "Once you’re lying flat, press the dumbbells up above your chest. This is your starting position.",
             "With a slight bend in your elbows, lower your arms laterally until you feel a stretch in your chest. The dumbbells should be level with your chest on both sides.",
             "Return your arms to the starting position and squeeze your pecs together. Remember to keep your arms steady throughout the movement.",
             "Don’t let the dumbbells touch as they meet at the top, holding for a second in the contracted position. Repeat the movement for the number of reps you need.",
        ],
},

{
  "id": 2,
  "title": "Rope Pull Down",
  "description": "A triceps-focused exercise using a cable machine to enhance arm strength and definition.",
  "image": require('@/assets/images/menu/RopePullDown.png'),
   "videoUrl": 'https://www.youtube.com/embed/RJa4kG1N3d0',
         "instructions": [
             "Sit down on a flat bench with a dumbbell in each hand resting on your thighs. (The palms of your hands should be facing each other).",
             "Lower yourself down until you’re lying flat. The dumbbell should remain close to your chest.",
             "Once you’re lying flat, press the dumbbells up above your chest. This is your starting position.",
             "With a slight bend in your elbows, lower your arms laterally until you feel a stretch in your chest. The dumbbells should be level with your chest on both sides.",
             "Return your arms to the starting position and squeeze your pecs together. Remember to keep your arms steady throughout the movement.",
             "Don’t let the dumbbells touch as they meet at the top, holding for a second in the contracted position. Repeat the movement for the number of reps you need.",
        ],
},

{
  "id": 3,
  "title": "Dumbbell Hammer Curls",
  "description": "A biceps exercise that emphasizes the brachialis muscle for increased arm thickness and strength.",
  "image": require('@/assets/images/menu/DumbbellHammerCurls.png'),
   "videoUrl": 'https://www.youtube.com/embed/RJa4kG1N3d0',
         "instructions": [
             "Sit down on a flat bench with a dumbbell in each hand resting on your thighs. (The palms of your hands should be facing each other).",
             "Lower yourself down until you’re lying flat. The dumbbell should remain close to your chest.",
             "Once you’re lying flat, press the dumbbells up above your chest. This is your starting position.",
             "With a slight bend in your elbows, lower your arms laterally until you feel a stretch in your chest. The dumbbells should be level with your chest on both sides.",
             "Return your arms to the starting position and squeeze your pecs together. Remember to keep your arms steady throughout the movement.",
             "Don’t let the dumbbells touch as they meet at the top, holding for a second in the contracted position. Repeat the movement for the number of reps you need.",
        ],
},
{
  "id": 4,
  "title": "Seated Dumbbell Curls",
  "description": "A classic biceps exercise performed while seated, helping to isolate the biceps for better muscle activation.",
  "image": require('@/assets/images/menu/SeatedDumbbellCurls.png'),
   "videoUrl": 'https://www.youtube.com/embed/RJa4kG1N3d0',
         "instructions": [
             "Sit down on a flat bench with a dumbbell in each hand resting on your thighs. (The palms of your hands should be facing each other).",
             "Lower yourself down until you’re lying flat. The dumbbell should remain close to your chest.",
             "Once you’re lying flat, press the dumbbells up above your chest. This is your starting position.",
             "With a slight bend in your elbows, lower your arms laterally until you feel a stretch in your chest. The dumbbells should be level with your chest on both sides.",
             "Return your arms to the starting position and squeeze your pecs together. Remember to keep your arms steady throughout the movement.",
             "Don’t let the dumbbells touch as they meet at the top, holding for a second in the contracted position. Repeat the movement for the number of reps you need.",
        ],
},
{
  "id": 5,
  "title": "Bench Dips",
  "description": "A bodyweight exercise targeting the triceps, performed with the hands resting on a bench and legs extended forward.",
    "image": require('@/assets/images/menu/BenchDips.png'),
    "videoUrl": 'https://www.youtube.com/embed/RJa4kG1N3d0',
         "instructions": [
             "Sit down on a flat bench with a dumbbell in each hand resting on your thighs. (The palms of your hands should be facing each other).",
             "Lower yourself down until you’re lying flat. The dumbbell should remain close to your chest.",
             "Once you’re lying flat, press the dumbbells up above your chest. This is your starting position.",
             "With a slight bend in your elbows, lower your arms laterally until you feel a stretch in your chest. The dumbbells should be level with your chest on both sides.",
             "Return your arms to the starting position and squeeze your pecs together. Remember to keep your arms steady throughout the movement.",
             "Don’t let the dumbbells touch as they meet at the top, holding for a second in the contracted position. Repeat the movement for the number of reps you need.",
        ],
},    
]