export const BackWorkouts = [
{
  "id": 1,
  "title": "Deadlift",
    "description": "A compound exercise targeting the posterior chain, including the lower back, glutes, and hamstrings.",
  "subtitle": "Targeted muscle group: The larger back muscles.",
    "image": require('@/assets/images/menu/Deadlift.png'),
  "videoUrl": 'https://www.youtube.com/embed/RJa4kG1N3d0',
         "instructions": [
             "Sit down on a flat bench with a dumbbell in each hand resting on your thighs. (The palms of your hands should be facing each other).",
             "Lower yourself down until you’re lying flat. The dumbbell should remain close to your chest.",
             "Once you’re lying flat, press the dumbbells up above your chest. This is your starting position.",
             "With a slight bend in your elbows, lower your arms laterally until you feel a stretch in your chest. The dumbbells should be level with your chest on both sides.",
             "Return your arms to the starting position and squeeze your pecs together. Remember to keep your arms steady throughout the movement.",
             "Don’t let the dumbbells touch as they meet at the top, holding for a second in the contracted position. Repeat the movement for the number of reps you need.",
        ],
},

{
  "id": 2,
  "title": "Lat Pulldown",
  "description": "A back-strengthening exercise that targets the latissimus dorsi, improving upper body pull strength.",
  "subtitle": "Targeted muscle group: The larger back muscles.",
  "image": require('@/assets/images/menu/LatPulldown.png'),"videoUrl": 'https://www.youtube.com/embed/RJa4kG1N3d0',
         "instructions": [
             "Sit down on a flat bench with a dumbbell in each hand resting on your thighs. (The palms of your hands should be facing each other).",
             "Lower yourself down until you’re lying flat. The dumbbell should remain close to your chest.",
             "Once you’re lying flat, press the dumbbells up above your chest. This is your starting position.",
             "With a slight bend in your elbows, lower your arms laterally until you feel a stretch in your chest. The dumbbells should be level with your chest on both sides.",
             "Return your arms to the starting position and squeeze your pecs together. Remember to keep your arms steady throughout the movement.",
             "Don’t let the dumbbells touch as they meet at the top, holding for a second in the contracted position. Repeat the movement for the number of reps you need.",
        ],
},

{
  "id": 3,
  "title": "Seated Cable Row",
  "description": "A compound exercise that strengthens the back, focusing on the lats, traps, and rhomboids.",
  "subtitle": "Targeted muscle group: The larger back muscles.",
  "image": require('@/assets/images/menu/SeatedCableRow.png'),"videoUrl": 'https://www.youtube.com/embed/RJa4kG1N3d0',
         "instructions": [
             "Sit down on a flat bench with a dumbbell in each hand resting on your thighs. (The palms of your hands should be facing each other).",
             "Lower yourself down until you’re lying flat. The dumbbell should remain close to your chest.",
             "Once you’re lying flat, press the dumbbells up above your chest. This is your starting position.",
             "With a slight bend in your elbows, lower your arms laterally until you feel a stretch in your chest. The dumbbells should be level with your chest on both sides.",
             "Return your arms to the starting position and squeeze your pecs together. Remember to keep your arms steady throughout the movement.",
             "Don’t let the dumbbells touch as they meet at the top, holding for a second in the contracted position. Repeat the movement for the number of reps you need.",
        ],
},
{
  "id": 4,
  "title": "Bent Over Barbell Row",
  "description": "A fundamental back exercise that targets the lats, traps, and rear delts while engaging the core.",
  "subtitle": "Targeted muscle group: The larger back muscles.",
  "image": require('@/assets/images/menu/BentOverBarbellRow.png'),
  "videoUrl": 'https://www.youtube.com/embed/RJa4kG1N3d0',
         "instructions": [
             "Sit down on a flat bench with a dumbbell in each hand resting on your thighs. (The palms of your hands should be facing each other).",
             "Lower yourself down until you’re lying flat. The dumbbell should remain close to your chest.",
             "Once you’re lying flat, press the dumbbells up above your chest. This is your starting position.",
             "With a slight bend in your elbows, lower your arms laterally until you feel a stretch in your chest. The dumbbells should be level with your chest on both sides.",
             "Return your arms to the starting position and squeeze your pecs together. Remember to keep your arms steady throughout the movement.",
             "Don’t let the dumbbells touch as they meet at the top, holding for a second in the contracted position. Repeat the movement for the number of reps you need.",
        ],
},
{
  "id": 5,
  "title": "Chin-Ups",
  "description": "A bodyweight exercise that primarily targets the biceps and upper back, improving grip strength and overall pulling power.",
  "subtitle": "Targeted muscle group: The larger back muscles.",
  "image": require('@/assets/images/menu/ChinUps.png'),
  "videoUrl": 'https://www.youtube.com/embed/RJa4kG1N3d0',
         "instructions": [
             "Sit down on a flat bench with a dumbbell in each hand resting on your thighs. (The palms of your hands should be facing each other).",
             "Lower yourself down until you’re lying flat. The dumbbell should remain close to your chest.",
             "Once you’re lying flat, press the dumbbells up above your chest. This is your starting position.",
             "With a slight bend in your elbows, lower your arms laterally until you feel a stretch in your chest. The dumbbells should be level with your chest on both sides.",
             "Return your arms to the starting position and squeeze your pecs together. Remember to keep your arms steady throughout the movement.",
             "Don’t let the dumbbells touch as they meet at the top, holding for a second in the contracted position. Repeat the movement for the number of reps you need.",
        ],
    },    
]