export const ChestWorkouts = [
    {
        "id": 1,
        "title": "Barbell Bench Press",
        "description": "A classic compound movement that strengthens the chest, shoulders, and triceps by pressing a barbell from the chest to a full extension.",
        "image": require('@/assets/images/menu/benchPress.png'),
        "videoUrl": 'https://www.youtube.com/embed/t1pmh-ajpqI?si=G62MhLn1UCqcbtMt',
        "subtitle": 'Targeted muscle group: The larger chest muscles.',
        "instructions": [
            "Lie flat on the bench press and grip the bar, with your hands just wider than your shoulders.",
            "Grip the bar slightly wider than shoulder-width apart (palms facing forward).",
            "Slowly lower the bar so that it touches your chest and hold this position for a second.",
            "Push the bar up in a fixed-line until your arms straighten. Hold this position for a second before repeating the process.",
            "Slight arch in your lower back is okay—keep your butt on the bench.",
            "Make sure your feet are flat on the floor at all times, with your hips on the bench.",
            "Aim for 3 sets of 8–10 repetitions."],
    },
    {
        "id": 2,
        "title": "Incline Dumbbell Press",
        "description": "A variation of the bench press focusing on the upper chest.",
        "image": require('@/assets/images/menu/InclineBenchPress.png'),
        "videoUrl": 'https://www.youtube.com/embed/t1pmh-ajpqI?si=G62MhLn1UCqcbtMt',
        "subtitle": 'Targeted muscle: Upper chest',
        "instructions": [
            "Set the bench to an incline (30°–45° is ideal).",
            "Sit down with a dumbbell in each hand, resting them on your thighs.",
            "Kick the dumbbells up one at a time as you lie back on the bench.",
            "Hold the dumbbells just outside your shoulders with palms facing forward.",
            "Muscle Growth (Hypertrophy): 3–4 sets of 8–12 reps",
        ],
    },
    {
        "id": 3,
        "title": "Cable Flys",
        "description": "An isolation exercise that targets the chest muscles using a cable machine for constant tension.",
        "image": require('@/assets/images/menu/cableFlys.png'),
        "videoUrl": 'https://www.youtube.com/embed/t1pmh-ajpqI?si=G62MhLn1UCqcbtMt',
        "subtitle": 'Targeted muscle: Upper chest',
        "instructions": [
            "Adjust the height of the pulley lever to be at shoulder height.",
            "Place yourself in the center of the pulley machine while holding the handle of each side.",
            "Brace your abdominals and take a step forward.",
            "Bring your arms up to shoulder height.",
            "Begin the movement by pushing the handles forward.",
            "Be sure to focus the contraction in your chest muscles.",
            "Once fully extended, pause then slowly release to the starting position.",
        ],
    },
    {
        "id": 4,
        "title": "Dumbbell Flys",
        "subtitle":"Targeted muscle group:  The pectoralis major and pectoralis minor.",
        "description": "A chest exercise that stretches and strengthens the chest muscles using dumbbells.",
        "image": require('@/assets/images/menu/dumbellFlys.png'),
         "videoUrl": 'https://www.youtube.com/embed/t1pmh-ajpqI?si=G62MhLn1UCqcbtMt',
         "instructions": [
             "Sit down on a flat bench with a dumbbell in each hand resting on your thighs. (The palms of your hands should be facing each other).",
             "Lower yourself down until you’re lying flat. The dumbbell should remain close to your chest.",
             "Once you’re lying flat, press the dumbbells up above your chest. This is your starting position.",
             "With a slight bend in your elbows, lower your arms laterally until you feel a stretch in your chest. The dumbbells should be level with your chest on both sides.",
             "Return your arms to the starting position and squeeze your pecs together. Remember to keep your arms steady throughout the movement.",
             "Don’t let the dumbbells touch as they meet at the top, holding for a second in the contracted position. Repeat the movement for the number of reps you need.",
        ],
    },
    {
        "id": 5,
        "title": "Decline Push-ups",
        "subtitle":"Targeted muscle: Chest, shoulders, and arms",
        "description": "A bodyweight exercise that targets the upper chest and shoulders by elevating the feet.",
        "image": require('@/assets/images/menu/declinePushups.png'),
        "videoUrl": 'https://www.youtube.com/embed/t1pmh-ajpqI?si=G62MhLn1UCqcbtMt',
         
         "instructions": [
             "Kneel down with your back to the bench. Put your hands on the floor, shoulders over your wrists and elbows at 45 degrees. Place your feet on top of the bench.",
             "Brace your core, glutes, and quads. Bend your elbows and lower your chest to the floor, keeping your back and neck straight.",
             "Push into the floor to return to starting position, extending your elbows.",
             "Complete 2 to 4 sets of 8 to 20 repetitions.",
        ],
    },
    
]